---
# tasks file for httpd
- name: Installing httpd
  yum:
    name: httpd
    state: latest
  notify: restart httpd

- name: start and enable httpd service
  service: 
    name: httpd
    state: started
    enabled: true

- name: Copying files
  copy:
    src: index.html
    dest: "{{ dest}}/index.html"
    mode: 0766
  notify: restart httpd
